### ISSUE TITLE
Use mixin tutorial Typo mistake?

### ISSUE THREAD

**Issue by Jaccouille** [AnyBlok/anyblok-book#11]
![roomFlushError](https://user-images.githubusercontent.com/7768858/61122006-f42fb280-a4a0-11e9-981b-f14098c1a0a4.jpg)

In https://anyblok.gitbooks.io/anyblok-book/content/en/03_blok/04_mixins.html

"_Note: room.flush() is used here to force sending data to the database as edit_date field is configured with auto_update option wich is called before sending data to the database._"

There is no "room.flush()" used in the code?

**Comment by jssuzanne** [comment]
There are no mistake.

**registry.flush()** is a shortcut to flush all the data cached in the SQLAlchemy session.

**Comment by Jaccouille** [comment]
Isn't it confusing to mention "room.flush() is used here"?

**Comment by jssuzanne** [comment]
Oh, my bad, i did not see the good line. you are rigth room.flush must removed
